//create array of meals
const meals = [{name:"BBQ Beef with Mac 'N Cheese", calories: 600, protein: 51, fat: 22, carbs: 54, src:'BBQ_Thin_2.png'},
		{name:"Pulled Pork Carnitas", calories: 480, protein: 50, fat: 20, carbs: 27, src:'Carnitas_Circle.png'},
		{name:"Chicken Enchilada Bake", calories: 530, protein: 38, fat: 21, carbs: 46, src:'Chicken_Enchilada_Bake.png'},
		{name:"Pork Bulgogi Bowl", calories: 550, protein: 37, fat: 21, carbs: 52, src:'Pork_Bulgogi_Bowl_Circle.png'},
		{name:"Simply Grilled Salmon", calories: 430, protein: 43, fat: 20, carbs: 20, src:'Simply_Salmon_Circle.png'},
		{name:"Mojito Lime Chicken", calories: 510, protein: 64, fat: 22, carbs: 12, src:'Mojito_Lime_Chicken_Circle.png'},
		{name:"Chicken Protein Potato Skins", calories: 520, protein: 42, fat: 18, carbs: 48, src:'Chicken_Protein_Skins_Circle.png'},
		{name:"Chicken Bruschetta", calories: 570, protein: 41, fat: 13, carbs: 72, src:'Bruschetta_Circle.png'},
		{name:"Apricot Glazed Chicken", calories: 560, protein: 47, fat: 15, carbs: 61, src:'Apricot_Thin_Circle.png'},
		{name:"Chicken Pad Thai", calories: 500, protein: 45, fat: 14, carbs: 47, src:'Pad_Thai_Thin.png'},
		{name:"3-Protein Mixed Grill", calories: 610, protein: 58, fat: 31, carbs: 18, src:'3_Protein_Mixed_Grill.jpg'},
		{name:"Grass Fed Bison Burger", calories: 410, protein: 27, fat: 18, carbs: 34, src:'Grass_Fed_Bison_Burger.jpg'},
		{name:"Honey Sriracha Chicken", calories: 570, protein: 51, fat: 27, carbs: 51, src:'Sriracha_Circle.png'},
        {name:"Chicken Pesto Tortellini", calories: 570, protein: 47, fat: 25, carbs: 44, src:'Chicken_Pesto_Circle.png'},
		{name:"Chicken Quesadilla", calories: 450, protein: 37, fat: 11, carbs: 53, src:'Chicken_Quesadilla_Circle.png'},
		{name:"Paleo Sloppy Joe", calories: 580, protein: 42, fat: 19, carbs: 60, src:'Paleo_Beef_Circle.png'},
		{name:"Mama’s Turkey Meatloaf", calories: 600, protein: 63, fat: 18, carbs: 51, src:'Mamas_Circle.png'},
		{name:"Jerk Chicken with Mac & Cheese", calories: 610, protein: 47, fat: 27, carbs: 43, src:'Jerk_Chicken_With_Mac_N__Cheese.jpg'},
		{name:"Dana's Chicken Cheesesteak", calories: 630, protein: 74, fat: 31, carbs: 14, src:'Dana_s_Chicken_Cheesesteak.jpg'},
		{name:"Cashew Chicken", calories: 480, protein: 35, fat: 16, carbs: 47, src:'Cashew_Circle.png'},
		{name:"Greek Meatballs", calories: 580, protein: 49, fat: 22, carbs: 46, src:'Greek_Meatballs.png'},
		{name:"Jamaican Pork Tenderloin", calories: 530, protein: 60, fat: 13, carbs: 36, src:'jamaican_pork.jpg'},
		{name:"Chicken & Vegetables", calories: 510, protein: 56, fat: 22, carbs: 18, src:'Chicken_Veg_Circle.png'},
        {name:"Miso Glazed Salmon", calories: 560, protein: 43, fat: 26, carbs: 40, src:'Miso_Salmon_Circle.png'},
        {name:"Supercharged Chicken", calories: 600, protein: 71, fat: 7, carbs: 60, src:'Supercharged_Chicken.jpg'},]